### ISSUE TITLE
[META] Wayland

### ISSUE THREAD

**Issue by ColinKinloch** [libretro/RetroArch#17310]
# Tasks
Here are some things I've been thinking about regarding wayland, I may add more if they occur to me.

* [ ] Don't destroy `wl_display` and `wl_surface` until quit
Currently gfx drivers are destroyed on core launch and fullscreen transitions.
This would allow the [splash screen](https://github.com/libretro/RetroArch/issues/14408) to be displayed on launch rather than on fullscreen and core transitions.
Currently the android keeps it's surface as a single surface is provided on application launch. It does this will a global if I recall correctly. Maybe window management should be split out of the gfx driver.

* [ ] xdg_toplevel configure events should stored until the xdg_surface configure at which point they're applied and `ack`ed
I think is handled correctly by libdecor but without libdecor currently RetroArch just `ack`s the configure.
https://github.com/libretro/RetroArch/blob/3e6486db2be523829bc22841c4a30b674978e9bf/input/common/wayland_common.c#L664-L669

* [ ] Bumb protocol versions
This can require implementing new event handlers, some of which are okay to ignore. However it can also require larger changes.

* [ ] Use `wl_event_queue` to decouple display and input threads
I'm not sure this would achieve anything.

* [ ] Drag and drop https://github.com/libretro/RetroArch/pull/16443
My attempt at implementing this crashes RetroArch and depends on glib for URI decoding.

# Testing strategy
Run nested kwin (env WAYLAND_DISPLAY=wayland-1):
```
kwin_wayland --xwayland --no-lockscreen  --width 1920 --height 1080 --output-count 2
```
Run nested mutter (env WAYLAND_DISPLAY=wayland-1):
```
MUTTER_DEBUG_DUMMY_MODE_SPECS=1920x1080 dbus-run-session -- mutter --nested --wayland
```
Run with limited CPU, useful for debugging race conditions:
```
systemd-run --user --pty --same-dir -p CPUQuota=1% env WAYLAND_DISPLAY=wayland-1 ./retroarch
```
Build without libdecor for testing raw xdg-toplevel implementation:
```
./configure --enable-debug --disable-libdecor
```

**Comment by Sunderland93** [comment]
Is `commit-timing-v1` and `fifo-v1` protocols also relevant?
