### ISSUE TITLE
[Meta] Ozone menu driver

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#7490]
**What needs to be done before having it enabled by default :**

- [ ] Implement missing features
    - [ ] Console tabs (+ sidebar scrolling)
    - [ ] OSK
    - [ ] Messagebox / dialogs
    - [ ] Fix multiline sublabels + add word wrapping (like materialui)
    - [ ] Battery display and icon
    - [ ] Add Y and X keys to bottom right text
- [ ] Fix floats issues on Switch
- [ ] Theme selection and override (light or dark is detected on the Switch depending on system theme, defaults to light on other platforms)
- [ ] Define `HAVE_OZONE` on all relevant platforms, add `HAVE_OZONE=auto` in `config.params.sh`

**Planned features :**
- [ ] Touch and mouse support
- [ ] Android layout (and darker theme ?)
    - [ ] Collapsible sidebar with hamburger button
    - [ ] Hide bottom right buttons indication
- [ ] Playlists layout and thumbnails (grid layout)

**Fancy shaders / menu display improvements :**
- [ ] Waving border color
- [ ] Blur (for playlists layout)
- [ ] Rounded rectangle cursor
- [ ] Box shadow around cursor

**Comment by RobLoach** [comment]
Tried this out, and it's great! Very clear, and easy to understand what you're looking at. Looking forward to seeing how this evolves :+1:

**Comment by m4xw** [comment]
@RobLoach make sure you try the dark theme too, it really is great.

**Comment by newget** [comment]
When I set language to english, it works fine with ozone.
But fonts are crashing if I set it to korean.
https://ibb.co/kOxSsq

xmb is working fine with korean lang.

**Comment by newget** [comment]
It's usable but Korean is not fully fixed yet.
It displays korean well in submenu, but not in header title.

Might be bold font problem?

**Comment by natinusala** [comment]
@newget https://github.com/libretro/retroarch-assets/pull/257

**Comment by fr500** [comment]
achievement badges are not showing up:

https://media.discordapp.net/attachments/501083188777713664/513860184850825217/unknown.png?width=1436&height=831

**Comment by Awakened0** [comment]
Drop shadow issue with the selector under Vulkan:
![prob](https://user-images.githubusercontent.com/4565863/48808984-c7037980-ecf0-11e8-803f-6193f660784a.png)

**Comment by zacly** [comment]
How long before thumbnails implemented? It's the only reason I haven't made the switch

**Comment by natinusala** [comment]
I first need to add scaling support. For scaling support I need to replace all the hardcoded metrics by actual variables and calculations.

So, not soon.

**Comment by fr500** [comment]
Hey, wanted to remind you that there are some crashes still:

1. Start core (use dosbox-svn, toggle the menu, crash)
2. Subsystem, load a game via subsystem with sameboy, toggle menu, crash

(gdb) bt
#0  0x00007ff8a223d0d1 in strlen () from C:\WINDOWS\System32\msvcrt.dll
#1  0x0000000000427fc9 in word_wrap ()
#2  0x00000000005999c4 in ozone_draw_entries ()
#3  0x000000000059725a in ozone_frame ()
#4  0x0000000000621d98 in gl_frame ()
#5  0x0000000000463c60 in video_driver_frame ()
#6  0x000000006cf4df76 in sameboy_libretro!retro_run ()
   from D:\GameData\Emulators\RetroArch\libretro\sameboy_libretro.dll
#7  0x0000000000402930 in core_run ()
#8  0x00000000005a13f5 in menu_driver_render ()
#9  0x00000000004041bd in runloop_check_state.constprop ()
#10 0x0000000000408005 in runloop_iterate ()
#11 0x0000000000401670 in rarch_main ()
#12 0x0000000000941358 in main_getcmdline ()
#13 0x00000000004013c7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:331
#14 0x00000000004014cb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:187

Same thing with start core in dosbox.
The problem is not in my code though, seems some function doesn't like empty strings

**Comment by natinusala** [comment]
@fr500 this PR should fix both crashes : https://github.com/libretro/RetroArch/pull/7644

**Comment by Awakened0** [comment]
I keep getting this missing asset error when using ozone on Windows nightlies despite updating my assets (just tested ac04c1bfc5ebba847557309aa6c55a55e0c05016):
`[WARN] [OZONE] Asset missing: F:\Blue\Emulation\Emulators\RetroArch\assets\ozone\png\.png`
`[WARN] [OZONE] Assets missing`

**Comment by natinusala** [comment]
@fr500 could it come from the newly created Discord avatar feature ?

**Comment by fr500** [comment]
Seems unlikely since I don't use the ozone dir at all.
I'll check that right now though

**Comment by natinusala** [comment]
I wondered because it only recently appeared and I didn't touch ozone for a while now. I will fix it before starting working back on it, so no rush

**Comment by fr500** [comment]
well I disabled a lot of my ozone.c code for now since I won't have much time till feb and threaded video is having so many issues external to this that I don't want to include more changes in the mix.

**Comment by bparker06** [comment]
scissor was added to d3d9/10/11 FYI

**Comment by daylerees** [comment]
This will be my default when the DPI fix is in place. Amazing work. Right now I'd need 5x better eyesight to use it on a 4K TV :)

**Comment by andiandi13** [comment]
@natinusala Anything new about playlist thumbnails grid layout ?

I did a quick edit and it would be so beautiful ! 

![gridozone](https://user-images.githubusercontent.com/19387072/85438753-96e72100-b58c-11ea-9403-404480b829dc.png)

**Comment by twinaphex** [comment]
I think this is definitely something that @jdgleaver has on his mind but it just takes a lot of time to refactor all the code in the menu driver to make this easily possible.

That being said, thanks for the mockup, and I do think something like that looks great, especially if we could even have additional size options so the user can control just how big the thumbnails should be.

**Comment by andiandi13** [comment]
I see, I'm looking forward to that option !

**Comment by natinusala** [comment]
I think the groundwork has been done (for Material UI), the plan was to add it to ozone after adding it to MUI

**Comment by jdgleaver** [comment]
Yes, we will most definitely be adding grid views. It'll take a little while, though - I still have to work out the required menu navigation changes, and then Material UI will be the first driver to get it (since this is already designed around the concept of multiple list view types). After that, it'll get ported to Ozone - this is quite a task, since it means replacing all of Ozone's thumbnail handling code with the routines we currently use in Material UI, and there will need to be some low-level redesign to support different view modes. But we'll get there, time permitting!

**Comment by notNSANE** [comment]
if Grid view gets added, plus a way to filter thousands of roms in a smart way (I discussed using Merged ROMs and only allowing the parent to show when adding a Playlist) it will make other frontends obsolete! :)
