### ISSUE TITLE
[Meta] Menu widgets

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#8198]
**What remains to be done**

- [ ] Add achievements notifications w/ badges (see #3946)
- [ ] Add netplay / Discord lobby join prompt
- [ ] Go through the whole RetroArch codebase and add a category and an icon to every call to `runloop_msg_queue_push` (~180 occurences)
- [ ] Add some degree of user customization
    - [ ] Disable load content animation
    - [ ] Disable menu widgets altogether
    - [x] Custom font
    - [ ] Custom colors
- [ ] Don't ignore the `Enable onscreen notifications` setting
- [ ] Have widgets enabled by default
- [ ] Implement menu widgets in all capable menu display drivers
    - [ ] D3D9
    - [ ] D3D10 & D3D11
    - [ ] D3D12
    - [ ] Vulkan
    - [ ] Metal
    - [ ] Wii U ? Vita ? 3DS ?

**Planned design changes**
 - [ ] Better shadow for notifications
 - [ ] Slim some parts down (especially volume and screenshot widgets)
 - [ ] Different load content animation
 - [ ] Add colors and icons for `SUCCESS`, `WARNING` and `ERROR` notifications

**Known issues**

 - [ ] When you reset the drivers (when loading or closing content), animations are killed but widgets are not, this yields "phantom" widgets that stay onscreen and never disappear. Fix : don't kill animations anymore when reloading the drivers
